pokemon_api_routes:
    resource: "@AppBundle/Controller/APIController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/routes

pokemon_api_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/user

pokemon_api_pokemon:
    resource: "@AppBundle/Controller/PokemonController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/pokemon

pokemon_api_attack:
    resource: "@AppBundle/Controller/AttackController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/attack

pokemon_api_area:
    resource: "@AppBundle/Controller/AreaController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/area

pokemon_api_trainer:
    resource: "@AppBundle/Controller/TrainerController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/trainer

pokemon_api_areatrainer:
    resource: "@AppBundle/Controller/AreaTrainerController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/areatrainer

pokemon_api_type:
    resource: "@AppBundle/Controller/TypeController.php"
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/type

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
